@MS-QUESTIONNAIRE_URL=http://127.0.0.1:3002


@QUESTIONNAIRE_ENDPOINT=questionnaire
@ANSWER_ENDPOINT=answer

### CREATE A NEW QUESTIONNAIRE
POST {{MS-QUESTIONNAIRE_URL}}/{{QUESTIONNAIRE_ENDPOINT}}
Content-Type: application/json
Authorization:

{
  "title": "Sample Questionnaire 1",
  "sections": [
    {
      "title": "Section 2",
      "questions": [
        {
          "content": "What is your favorite color?",
          "observation": "Pick one color",
          "answers": [
            { "content": "Red" },
            { "content": "Blue" },
            { "content": "Green" }
          ]
        },
        {
          "content": "Explain your answer",
          "observation": "Provide a short explanation",
          "answers": [
            { "content": "SI" },
            { "content": "NO" }
          ]
        }
      ]
    }
  ]
}

### GET QUESTIONNAIRES
GET {{MS-QUESTIONNAIRE_URL}}/{{QUESTIONNAIRE_ENDPOINT}}

### GET QUESTIONNAIRE BY ID
GET {{MS-QUESTIONNAIRE_URL}}/{{QUESTIONNAIRE_ENDPOINT}}/ID_HERE

### DELETE QUESTIONNAIRE BY ID
DELETE {{MS-QUESTIONNAIRE_URL}}/{{QUESTIONNAIRE_ENDPOINT}}/ID_HERE